% -------------------------------------------------------------------
%  Generated by MATLAB on 13-Aug-2022 19:14:14
%  MATLAB version: 9.12.0.1975300 (R2022a) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('robot_DataFile.mat');

motion_time_constant = 0.005;

smiData = saveVarsMat.smiData; % <1x1 struct> unsupported class at smiData.RigidTransform(1).ID

clear saveVarsMat;
